# Generated by Django 4.2.7 on 2026-01-13 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_knowledgebase_approved_knowledgebase_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admin_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Role-based permissions'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('department_admin', 'Department Admin'), ('super_admin', 'Super Admin')], default='department_admin', max_length=50),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Response confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='source_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details about response source (KB ID, matching score, etc.)'),
        ),
        migrations.AddField(
            model_name='document',
            name='target_departments',
            field=models.JSONField(blank=True, default=list, help_text='List of department names for department visibility'),
        ),
        migrations.AddField(
            model_name='document',
            name='target_user_groups',
            field=models.JSONField(blank=True, default=list, help_text='Specific user groups who can access'),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - All Users'), ('department', 'Department Only'), ('private', 'Private - Admin Only')], default='public', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('user_activity', 'User Activity Report'), ('admin_activity', 'Admin Activity Report'), ('ai_usage', 'AI Usage Report'), ('system_performance', 'System Performance Report'), ('analytics', 'Analytics Report')], max_length=50)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Report generation parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Report',
                'verbose_name_plural': 'System Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('document', 'New Document'), ('announcement', 'Announcement'), ('update', 'Content Update'), ('system', 'System Notification'), ('reminder', 'Reminder')], default='announcement', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like document ID, link, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_queries/')),
                ('query_text', models.TextField(blank=True, help_text='Optional text query about the image', null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Query',
                'verbose_name_plural': 'Image Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Document Upload'), ('update', 'Update'), ('delete', 'Delete'), ('create', 'Create'), ('approve', 'Approve'), ('reject', 'Reject'), ('notification', 'Send Notification')], max_length=50)),
                ('target_type', models.CharField(choices=[('document', 'Document'), ('kb_entry', 'Knowledge Base Entry'), ('user', 'User'), ('admin', 'Admin'), ('rule', 'Rule'), ('syllabus', 'Syllabus'), ('exam', 'Exam Information'), ('notification', 'Notification')], max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_title', models.CharField(blank=True, help_text='Human readable title of target', max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
