# Generated by Django 4.2.7 on 2026-01-18 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_adminprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('chat_history', 'user')},
        ),
    ]
