# Generated by Django 4.2.7 on 2026-01-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_adminprofile_approval_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
    ]
