# Generated by Django 4.2.7 on 2026-01-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_adminprofile_approval_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperAdminOfCollege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Super Admin of College",
                "verbose_name_plural": "Super Admins of College",
            },
        ),
    ]
