# Generated by Django 4.2.7 on 2026-01-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adminprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='helpful_feedback',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='not_helpful_feedback',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
