# Generated by Django 4.2.7 on 2026-01-18 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_superadminofcollege"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuperAdminOfCollege",
        ),
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("chat_history", "user")},
        ),
    ]
