# Generated by Django 4.2.7 on 2026-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_analytics_helpful_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="User feedback comments", null=True
            ),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="is_helpful",
            field=models.BooleanField(
                blank=True,
                help_text="User feedback: True for helpful, False for not helpful",
                null=True,
            ),
        ),
    ]
