# Generated by Django 4.2.7 on 2026-01-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chathistory_feedback_chathistory_is_helpful'),
        ('core', '0009_chathistory_feedback_chathistory_is_helpful'),
    ]

    operations = [
    ]
