# Generated by Django 4.2.7 on 2026-01-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chathistory',
            name='intent',
            field=models.CharField(blank=True, choices=[('kb_match', 'Knowledge Base Match'), ('ai_fallback', 'AI Fallback'), ('error', 'Error')], help_text='Response intent/source', max_length=20, null=True),
        ),
    ]
