# Generated by Django 4.2.7 on 2026-01-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chathistory_confidence_score_chathistory_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='blob_content',
            field=models.BinaryField(blank=True, help_text='Compressed file content stored as BLOB', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_compressed',
            field=models.BooleanField(default=False, help_text='Whether the BLOB content is compressed with zlib'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to uploaded file', max_length=500, null=True),
        ),
    ]
