# Generated by Django 4.2.7 on 2026-01-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_blob_content_document_is_compressed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
