# Generated by Django 4.2.7 on 2026-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology', 'Information Technology'), ('Electronics & Communication', 'Electronics & Communication'), ('Electrical & Electronics', 'Electrical & Electronics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Biotechnology', 'Biotechnology'), ('Aerospace Engineering', 'Aerospace Engineering'), ('B.Sc Computer Science', 'B.Sc Computer Science'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('Other', 'Other')], max_length=100),
        ),
    ]
