# Generated by Django 4.2.7 on 2026-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studentprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='target_years',
            field=models.JSONField(blank=True, default=list, help_text='List of academic years (e.g., 1st Year, 2nd Year)'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='intent',
            field=models.CharField(blank=True, choices=[('kb_match', 'Knowledge Base Match'), ('ai_fallback', 'AI Fallback'), ('document_suggestion', 'Document Suggestion'), ('error', 'Error')], help_text='Response intent/source', max_length=20, null=True),
        ),
    ]
